version: 0.1
phases:
  install:
    commands:
      - pip install pytest
  build:
    commands:
      - python -m pytest tests
      - aws cloudformation package --template-file template.yaml --s3-bucket waf-ip-set-cleanup-code-bucket --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
